server:
  servlet:
    context-path: /devops
    session:
      cookie:
        http-only: true
        domain: localhost
        name: sessionId
  port: 8888
spring:
  application:
    name: devops
  aop:
    proxy-target-class: true

  datasource:
    url: jdbc:mysql://localhost:3306/devops_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .html
    request-context-attribute: request
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    locale: zh_CN
    locale-resolver: fixed
    throw-exception-if-no-handler-found: true

  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    database: mysql
  task:
    execution:
      pool:
        max-size: 10
      thread-name-prefix: async-service-
logging:
  level:
    org.springframework.web: info

application:
  clone:
    location: D:/develop/software/JAVA/Iproject/application/
  package:
    save-location: D:/develop/software/JAVA/Iproject/localRepository